/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Committee = Member[];

export interface Member {
  /**
   * The first name of the committee member
   */
  firstName: string;
  /**
   * The last name of the committee member
   */
  lastName: string;
  /**
   * The nationality of the committee member, using a 2-letter code.
   * Can be checked at https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/4.1.4/flags/4x3/at.svg
   */
  countryCode: string;
  /**
   * The role of the committee member
   */
  role?: ("chair" | "deputy-chair") & string;
  past?: boolean;
}
