name: Deploy to GitHub Pages
on: 
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy:
    uses: EndBug/workflows/.github/workflows/deploy-gh-pages-with-preview.yml@main
    with:
      folder: out
