name: Preview PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./out/
